apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    version: mirror
  name: server-mirror
  namespace: mirror-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: mirror
  template:
    metadata:
      labels:
        app: server
        version: mirror
    spec:
      containers:
      - image: didiyudha/server-app:mirror
        imagePullPolicy: Always
        name: server-mirror
        ports:
          - containerPort: 8080
            protocol: TCP
