apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    version: v1
  name: server-v1
  namespace: mirror-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: v1.0.0
  template:
    metadata:
      labels:
        app: server
        version: v1.0.0
    spec:
      containers:
      - image: didiyudha/server-app:v1.0.0
        imagePullPolicy: Always
        name: server
        ports:
          - containerPort: 8080
            protocol: TCP
