apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    version: v2
  name: server-v2
  namespace: mirror-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: v2
  template:
    metadata:
      labels:
        app: server
        version: v2
    spec:
      containers:
      - image: didiyudha/server:v2
        imagePullPolicy: Always
        name: server
        ports:
          - containerPort: 8080
            protocol: TCP
