apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: mirror-traffic
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: server
  type: ClusterIP
